kamlesh_friend/employee/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from employee import views

urlpatterns = [
    url(r'^$', views.employee_details, name='employee'),
    url(r'^about$', views.about, name='abouturl'),
    url(r'^employee/details$', views.emp_details, name='emp_details'),
    url(r'^employee/salary/$', views.salary_detail, name='salary_details'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^view_details$', views.view_details, name='view_details'),
    url(r'^change_password$', views.change_password, name='change_password'),
    url(r'^view_salary/(?P<x>\d+)/$', views.view_salary, name='view_salary'),
    url(r'^delete_data/(?P<x>\d+)/$', views.delete_data, name='delete_data'),
]

kamlesh_friend/homepage/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.homepage, name='homepage'),
    
    url(r'^about$', views.about, name='abouturl'),
    url(r'^details$', views.details, name='module_details'),
    url(r'^contact$', views.contact, name='contact_me'),
    url(r'^loginme/$', views.log_in, name='loginme'),
    # url(r'^login/$', auth_views.login, {'template_name': 'homepage/log_in_employee.html'}, name='login'),
    url(r'^signup$', views.sign_up, name='signupme'),
]

kamlesh_friend/payroll/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [   url(' ', include('travel.urls',namespace='index')),
                  url(r'^admin/', admin.site.urls),

                  url(r'^', include('homepage.urls', namespace='homepageurl')),
                  url(r'^employee/', include('employee.urls', namespace='empurl')),
                  url(r'^payroll_admin/', include('payroll_admin.urls', namespace='payrollurl')),

                  url('^', include('django.contrib.auth.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kamlesh_friend/payroll_admin/urls.py
from django.conf.urls import url

from payroll_admin import views

urlpatterns = [
    url(r'^$', views.admin_payroll, name='payroll_login'),
    url(r'^about_admin$', views.admin_about, name='admin_about'),
    url(r'^add_department$', views.add_department, name='add_depart'),
    url(r'^admin_destination$', views.admin_destination_data, name='admin_destination'),
    # url(r'^edit_depart/(?P<x>\d+)/$', views.edit_depart,name='edit_depart'),

    url(r'^add_designation$', views.add_designation, name='add_design'),
    url(r'^add_salary$', views.add_salary, name='add_salary'),
    url(r'^admin_report$', views.admin_report, name='admin_report'),
    url(r'^department_report$', views.department_report, name='department_report'),
    url(r'^designation_report$', views.designation_report, name='designation_report'),
    url(r'^employee_report$', views.employee_report, name='employee_report'),
    url(r'^salary_report$', views.salary_report, name='salary_report'),
    url(r'^salaryedit/(?P<x>\d+)/(?P<y>\d+)$', views.salaryedit, name='salaryedit'),

    url(r'^admin_account$', views.admin_account_info, name='admin_account'),
    url(r'^admin_salary$', views.admin_salary, name='admin_salary'),
    url(r'^admin_view_details$', views.admin_view_details, name='admin_view_details'),
    url(r'^admin_admin_salary$', views.admin_admin_salary, name='admin_admin_salary'),
    url(r'^delete/(?P<x>\d+)/$', views.delete, name='delete'),
    url(r'^view_salary_admin/(?P<x>\d+)/$', views.view_salary_admin, name='view_salary_admin'),
    url(r'^delete_admin/(?P<x>\d+)/$', views.delete_admin, name='delete_admin'),
    url(r'^salary_delete/(?P<x>\d+)/$', views.salary_delete, name='salary_delete'),
    url(r'^delete_salary_admin/(?P<x>\d+)/$', views.delete_salary_admin, name='delete_salary_admin'),
    url(r'^delete_department/(?P<x>\d+)/$', views.delete_department, name='delete_department'),
    url(r'^delete_designation/(?P<x>\d+)/$', views.delete_designation, name='delete_designation'),
    url(r'^delete_emp/(?P<x>\d+)/$', views.delete_emp, name='delete_emp'),
    # url(r'^edit_admin/(?P<x>\d+)/$', views.edit_admin,name='edit_admin'),

]

kamlesh_friend/travel/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index')
    # url(r'^about$', views.about, name='abouturl'),
    # url(r'^details$', views.details, name='module_details'),
    # url(r'^contact$', views.contact, name='contact_me'),
    # url(r'^loginme/$', views.log_in, name='loginme'),
    # # url(r'^login/$', auth_views.login, {'template_name': 'homepage/log_in_employee.html'}, name='login'),
    # url(r'^signup$', views.sign_up, name='signupme'),
]

kamlesh_friend/payroll_admin/views.py
from django.contrib import messages
from django.shortcuts import render, redirect

from employee.models import emp_account
from .models import admin_destination
from homepage.models import Regis_db
from .models import admin_model,admin_destination, add_department_model, add_designation_model, salary_details, admin_account, \
    add_admin_sal






def admin_payroll(request):
    if 'admin_username' in request.session:
        admin_username = request.session['admin_username']
        return redirect('payrollurl:admin_about')
    elif request.method == 'POST':
        admin_username = request.POST["admin_username"]
        p = request.POST["admin_password"]

        if (len(admin_model.objects.filter(admin_username=admin_username)) and admin_model.objects.filter(admin_password=p)):
            request.session['admin_username'] = admin_username
            print("admin session start")
            return redirect('payrollurl:admin_about')
        else:
            messages.warning(request, 'Username Or Password Wrong')

    return render(request, 'payroll_admin/payroll_login.html')


def admin_about(request):
    return render(request, 'payroll_admin/admin_about.html')


def add_department(request):
    if request.method == "POST":
        add_department = request.POST['add_department']
        description = request.POST['description']

        reg_db_obj = add_department_model()
        reg_db_obj.add_department = add_department
        reg_db_obj.description = description

        reg_db_obj.save()
        messages.success(request, 'Department add successfully')

        return redirect('payrollurl:add_depart')
    return render(request, 'payroll_admin/admin_department.html')


def add_designation(request):
    if request.method == "POST":
        add_designation = request.POST['add_designation']
        description = request.POST['description']

        reg_db_obj = add_designation_model()
        reg_db_obj.add_designation = add_designation
        reg_db_obj.description = description
        reg_db_obj.save()
        messages.success(request, 'Designation add successfully')

        return redirect('payrollurl:add_design')
    return render(request, 'payroll_admin/add_designation.html')


# Create your views here.
def add_salary(request):
    e = emp_account.objects.all()
    r=Regis_db.objects.all()
    print(e)
    if request.method == "POST":
        emp_name = request.POST['emp_name']
        user_name=request.POST['user_name']
        mp = request.POST['mp']
        working_days = request.POST['working_days']
        bs = request.POST['bs']
        house_rent = request.POST['house_rent']
        mediclaim = request.POST['mediclaim']
        travel = request.POST['travel']
        dearness = request.POST['dearness']
        reimburement = request.POST['reimburement']
        conveyance = request.POST['conveyance']
        other_salary = request.POST['other_salary']
        year_salary = request.POST['year_salary']
        provident_fund = request.POST['provident_fund']
        total_tax = request.POST['total_tax']
        total_deduction = request.POST['total_deduction']
        total_salary = request.POST['total_salary']

        sal_obj = salary_details()
        sal_obj.emp_name = emp_name
        sal_obj.mp = mp
        sal_obj.working_days = working_days
        sal_obj.bs = bs
        sal_obj.house_rent = house_rent
        sal_obj.mediclaim = mediclaim
        sal_obj.travel = travel
        sal_obj.dearness = dearness
        sal_obj.reimburement = reimburement
        sal_obj.conveyance = conveyance
        sal_obj.other_salary = other_salary
        sal_obj.year_salary = year_salary
        sal_obj.provident_fund = provident_fund
        sal_obj.total_tax = total_tax
        sal_obj.total_deduction = total_deduction
        sal_obj.total_salary = total_salary

        sal_obj.user_name_id = user_name
        print(sal_obj.user_name_id)
        sal_obj.save()
        messages.success(request, 'saved')
        return redirect('payrollurl:add_salary')

    return render(request, 'payroll_admin/add_salary.html', {'data': e,'emp':r})


def admin_report(request):
    e = admin_account.objects.all()
    return render(request, 'payroll_admin/admin_report.html', {'data': e})


def delete_admin(request, x):
    e = admin_account.objects.filter(user_name_id=x)
    e.delete()
    return redirect('payrollurl:admin_report')


def department_report(request):
    obj = add_department_model.objects.all()
    return render(request, 'payroll_admin/department_report.html', {'data': obj})


def designation_report(request):
    obj = add_designation_model.objects.all()
    return render(request, 'payroll_admin/designation_report.html', {'data': obj})


def employee_report(request):
    obj = emp_account.objects.all()
    obj1 = Regis_db.objects.all()
    return render(request, 'payroll_admin/employee_report.html', {'data': obj, 'data1': obj1})


def salary_report(request):
    obj1 = salary_details.objects.all()
    obj2 = add_admin_sal.objects.all()

    return render(request, 'payroll_admin/salary_report.html', {'data1': obj1, 'data2': obj2})


def salaryedit(request, x, y):
    e = salary_details.objects.filter(id=x)
    a = emp_account.objects.filter(user_name_id=y)

    return render(request, 'payroll_admin/view_salary_admin.html', {'admin': e, 'sal': a})


def admin_account_info(request):
    s = admin_model.objects.filter(admin_username=request.session['admin_username'])
    e = admin_account.objects.filter(
        user_name=admin_model.objects.filter(admin_username=request.session['admin_username']))

    if request.method == "POST":
        department = request.POST['department']
        designation = request.POST['designation']
        gender = request.POST['gender']
        fullname = request.POST['fullname']
        mobile = request.POST['mobile']
        bday = request.POST['bday']
        add1 = request.POST['add1']
        add2 = request.POST['add2']
        city = request.POST['city']
        state = request.POST["state"]
        country = request.POST['country']
        account = request.POST['account']
        bank = request.POST['bank']
        email = request.POST['email']
        pfaccount = request.POST['pfaccount']
        joining_date = request.POST['joining_date']
        emp_obj = admin_account(filename=request.FILES['filename'])
        emp_obj.department = department
        emp_obj.designation = designation
        emp_obj.gender = gender
        emp_obj.mobile = mobile
        emp_obj.add1 = add1
        emp_obj.bday = bday
        emp_obj.add2 = add2
        emp_obj.city = city
        emp_obj.email = email
        emp_obj.fullname = fullname
        emp_obj.state = state
        emp_obj.country = country
        emp_obj.account = account
        emp_obj.bank = bank
        emp_obj.pfaccount = pfaccount
        emp_obj.joining_date = joining_date
        print(request.session['admin_username'])
        emp_obj.user_name = admin_model.objects.get(admin_username=request.session['admin_username'])
        emp_obj.save()

        messages.success(request, 'saved')
        return render(request, 'payroll_admin/admin_account.html')

    return render(request, 'payroll_admin/admin_account.html', {'data': s, 'data1': e})


# def edit_admin(request,x):
#
#     return redirect('payrollurl:admin_account',{'data':e})


def admin_salary(request):
    obj2 = add_admin_sal.objects.filter(
        user_name=admin_model.objects.filter(admin_username=request.session['admin_username']))
    return render(request, 'payroll_admin/admin_salary.html', {'data': obj2})


def admin_view_details(request):
    s = admin_model.objects.filter(admin_username=request.session['admin_username'])
    e = admin_account.objects.filter(
        user_name=admin_model.objects.filter(admin_username=request.session['admin_username']))
    print(e)

    return render(request, 'payroll_admin/admin_view_details.html', {'data': e, 'data1': s})


def admin_admin_salary(request):
    user_name_id = admin_model.objects.filter(admin_username=request.session['admin_username'])
    print(user_name_id)

    e = admin_account.objects.filter(
        user_name=admin_model.objects.filter(admin_username=request.session['admin_username']))
    if request.method == "POST":
        emp_name = request.POST['emp_name']
        mp = request.POST['mp']
        working_days = request.POST['working_days']
        bs = request.POST['bs']
        house_rent = request.POST['house_rent']
        mediclaim = request.POST['mediclaim']
        travel = request.POST['travel']
        dearness = request.POST['dearness']
        reimburement = request.POST['reimburement']
        conveyance = request.POST['conveyance']
        other_salary = request.POST['other_salary']
        year_salary = request.POST['year_salary']
        provident_fund = request.POST['provident_fund']
        total_tax = request.POST['total_tax']
        total_deduction = request.POST['total_deduction']
        total_salary = request.POST['total_salary']

        sal_obj = add_admin_sal()
        sal_obj.admin_name = emp_name
        sal_obj.mp = mp
        sal_obj.working_days = working_days
        sal_obj.bs = bs
        sal_obj.house_rent = house_rent
        sal_obj.mediclaim = mediclaim
        sal_obj.travel = travel
        sal_obj.dearness = dearness
        sal_obj.reimburement = reimburement
        sal_obj.conveyance = conveyance
        sal_obj.other_salary = other_salary
        sal_obj.year_salary = year_salary
        sal_obj.provident_fund = provident_fund
        sal_obj.total_tax = total_tax
        sal_obj.total_deduction = total_deduction
        sal_obj.total_salary = total_salary
        sal_obj.user_name_id = admin_model.objects.filter(admin_username=request.session['admin_username'])

        sal_obj.save()
        messages.success(request, 'saved')
        return redirect('payrollurl:admin_admin_salary')

kamlesh_friend/payroll_admin/templates/payroll_admin/admin_about.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'homepage/homepage.css' %}"/>
<link rel="stylesheet" type="text/css" href="{% static 'homepage/animate.css' %}"/>


<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title%}Admin Account{%endblock%}</title>
</head>

<body>

<nav class="navbar navbar-expand-lg navbar-light fixed-top bg-light ">
    <a class="navbar-brand" href="{% url 'homepageurl:homepage' %}"> <img class="img-fluid"
                                                                          src="{% static 'homepage/images/logo.png' %}"
                                                                          alt="My image"
                                                                          style="width:30px"/>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

            <li class="nav-item active">
                <a class="nav-link" href="{% url 'payrollurl:admin_about' %}"><img
                        src="{% static 'homepage/images/about1.png' %}">About</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Administration
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'payrollurl:add_depart' %}"><img
                            src="{% static 'payroll_admin/images/add.png' %}">Add department</a>
                    <a class="dropdown-item" href="{% url 'payrollurl:add_design' %}"><img
                            src="{% static 'payroll_admin/images/add.png' %}">Add Designation</a>
                    <a class="dropdown-item" href="{% url 'payrollurl:add_salary' %}"><img
                            src="{% static 'payroll_admin/images/add.png' %}">Add Salary Of Employee</a>
                    <a class="dropdown-item" href="{% url 'payrollurl:admin_admin_salary' %}"><img
                            src="{% static 'payroll_admin/images/add.png' %}">Add Salary Of Admin</a>

                </div>
            </li>


            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownLink" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Reports
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'payrollurl:admin_report' %}"><img
                            src="{% static 'payroll_admin/images/report.png' %}">System Admin Report</a>
                    <a class="dropdown-item" href="{% url 'payrollurl:department_report' %}"><img
                            src="{% static 'payroll_admin/images/report.png' %}">Departments Report</a>
                    <a class="dropdown-item" href="{% url 'payrollurl:employee_report' %}"><img
                            src="{% static 'payroll_admin/images/report.png' %}">Employee Report</a>
                    <a class="dropdown-item" href="{% url 'payrollurl:designation_report' %}"><img
                            src="{% static 'payroll_admin/images/report.png' %}">Designation Report</a>
                    <a class="dropdown-item" href="{% url 'payrollurl:salary_report' %}"><img
                            src="{% static 'payroll_admin/images/report.png' %}">Salary Report</a>
                </div>
            </li>


            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownLi" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Account
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'payrollurl:admin_account' %}"><img
                            src="{% static 'homepage/images/login.png' %}">My Account</a>
                    <a class="dropdown-item" href="{% url 'payrollurl:admin_salary' %}"><img
                            src="{% static 'homepage/images/login.png' %}">My Salary</a>


                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'empurl:logout' %}"><img
                        src="{% static 'homepage/images/about1.png' %}">Logout</a>
            </li>


            <li class="nav-item">
                <a class="nav-link disabled" href="#"></a>
            </li>
        </ul>
        <span class="navbar-text">
    <b><i class="animated hinge" style="color:SlateBlue;font-family:verdana;font-size:120%;"><img class="animated hinge"
                                                                                                  src="{% static 'homepage/images/logo4.png' %}">Payroll Management System</i></b>
  </span>

    </div>
</nav>
{%block body%}
<br>
<br>
<br>

<div class="container-fluid" style="background-color:#64677F;height:60px">
    <div class="col-sm-4">
        <h3 class="animated bounceInLeft" align="center" style="color:white;hight:40px;padding-top:10px">About
            Admin</h3>
    </div>

    <br>
    <br>
    <br>
    <br>
</div>
<br>


<div class="container">
    <h2 style="font-size:25px;color:gray;">
        These are Functionality Performed by the admin users.
    </h2>
    <br>
    <br>

    <h6>1. Login For Admin</h6>
    <h6>2. Edit Profile For Admin</h6>
    <h6>3. Change Password Admin</h6>
    <h6>4. Logout Functionality</h6>
    <h6>5. Dashboard for Admin User</h6>
    <h6>6. Manage Department</h6>

    <ul class="a">
        <li>Adding New Department</li>
        <li>Edit The Existing DEpartment</li>
        <li>View Details Of The Department</li>
        <li>Listing of all Department</li>
    </ul>
    <h6>7. Manage Designation</h6>

    <ul class="a">
        <li>Adding New Designation</li>
        <li>Edit the Existing Designation</li>
        <li>View Details of the Designation</li>
        <li>Listing Of All Designation</li>
    </ul>
    <h6>8. Manage Employee</h6>

    <ul class="a">
        <li>Adding New Employee</li>
        <li>Edit the Existing Employee</li>
        <li>View Details of the Employee</li>
        <li>Listing Of All Employee</li>
    </ul>

    <h6>9. Manage Salary</h6>

    <ul class="a">
        <li>Adding New Salary</li>
        <li>Edit the Existing Salary</li>
        <li>View Details of the Salary</li>
        <li>Listing Of All Salary</li>
    </ul>
    <h6>9. Manage Reports of the Project</h6>

    <ul class="a">
        <li>Report of all Department</li>
        <li>Report of all Designation</li>
        <li>Report of all Employees</li>
        <li>Reports of all Salary</li>
    </ul>

</div>
{%endblock%}
<hr>

<footer>
    <div class="row">
        <div class="col-sm-6">
            <b class="animated bounceInLeft" style="font-size:18px;color:#F2F1F7">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CONTACT
                INFO:</b>&nbsp;
            <p class="animated bounceInLeft" style="font-size:14px;color:#F2F1F7">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img
                    src="{% static 'homepage/images/add1.png' %}">&nbsp;Address:New Ashok Nagar,Delhi</p>
            <p class="animated bounceInLeft" style="font-size:14px;color:#F2F1F7">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img
                    src="{% static 'homepage/images/city.png' %}">&nbsp;Main City:Delhi</p>
            <p class="animated bounceInLeft" style="font-size:14px;color:#F2F1F7">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img
                    src="{% static 'homepage/images/mobile.png' %}">&nbsp;Mobile No:9639830975</p>
            <p class="animated bounceInLeft" style="font-size:14px;color:#F2F1F7">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img
                    src="{% static 'homepage/images/phon.png' %}">&nbsp;Phon No:0122-2362458</p>
            <p class="animated bounceInLeft" style="font-size:14px;color:#F2F1F7">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img
                    src="{% static 'homepage/images/email3.png' %}">&nbsp;Email: <a style="color:white"
                                                                                    href="mailto:deegariya007@gmail.com">deegariya007@gmail.com</a>
            </p>
        </div>
        <div class="col-sm-6">
            <div id="map" style="width:200pxheight:250pxpx"></div>

            <script>
function myMap() {
  var mapCanvas = document.getElementById("map");
  var myCenter = new google.maps.LatLng(28.5911307,77.3078392);
  var mapOptions = {center: myCenter, zoom: 5};
  var map = new google.maps.Map(mapCanvas,mapOptions);
  var marker = new google.maps.Marker({
    position: myCenter,
    animation: google.maps.Animation.BOUNCE
  });
  marker.setMap(map);
}








            </script>

            <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA8PG7PfjhaZVR6EEbEy4c95CHOdNTmjw4&callback=myMap"></script>
        </div>
    </div>

</footer>
<footer style="background-color:black">
    <div class="row">


        <div class="col-sm-3">
            <p style="color:white;font-size:12px;padding-top:5px;padding-left:5px;">Major Project:MCA © 2018 All Rights
                Reserved.

            </p>
        </div>
        <div class="col-sm-3">
            <ul style="list-style-type:none">
                <li style="float:left;padding-top:7px">
                    <p style="color:white;font-size:12px">Follow me on:</p>
                </li>
                <li style="float:left">
                    <a href="https://www.facebook.com/deepak.gariya"> <img src="{% static 'homepage/images/fb1.png' %}"
                                                                           style="hight:27px;width:27px;padding-top:5px;padding-left:5px"></a>

                </li>
                <li style="float:left">
                    <a href="https://twitter.com/Deepakgariya1"> <img src="{% static 'homepage/images/twitter.png' %}"
                                                                      style="hight:27px;width:27px;padding-top:5px;padding-left:5px"></a>

                </li>
                <li style="float:left">
                    <a href="https://www.linkedin.com/in/deepak-gariya-3ab5b495
"><img src="{% static 'homepage/images/linkedin.png' %}"
       style="hight:27px;width:27px;padding-top:5px;padding-left:5px"></a>

                </li>


            </ul>
        </div>

    </div>
</footer>
</body>
</html>