kamlesh_friend/homepage/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.homepage, name='homepage'),
    
    url(r'^about$', views.about, name='abouturl'),
    url(r'^details$', views.details, name='module_details'),
    url(r'^contact$', views.contact, name='contact_me'),
    url(r'^loginme/$', views.log_in, name='loginme'),
    # url(r'^login/$', auth_views.login, {'template_name': 'homepage/log_in_employee.html'}, name='login'),
    url(r'^signup$', views.sign_up, name='signupme'),
]

kamlesh_friend/payroll/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [   url(' ', include('travel.urls',namespace='index')),
                  url(r'^admin/', admin.site.urls),

                  url(r'^', include('homepage.urls', namespace='homepageurl')),
                  url(r'^employee/', include('employee.urls', namespace='empurl')),
                  url(r'^payroll_admin/', include('payroll_admin.urls', namespace='payrollurl')),

                  url('^', include('django.contrib.auth.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kamlesh_friend/payroll_admin/urls.py
from django.conf.urls import url

from payroll_admin import views

urlpatterns = [
    url(r'^$', views.admin_payroll, name='payroll_login'),
    url(r'^about_admin$', views.admin_about, name='admin_about'),
    url(r'^add_department$', views.add_department, name='add_depart'),
    url(r'^admin_destination$', views.admin_destination_data, name='admin_destination'),
    # url(r'^edit_depart/(?P<x>\d+)/$', views.edit_depart,name='edit_depart'),

    url(r'^add_designation$', views.add_designation, name='add_design'),
    url(r'^add_salary$', views.add_salary, name='add_salary'),
    url(r'^admin_report$', views.admin_report, name='admin_report'),
    url(r'^department_report$', views.department_report, name='department_report'),
    url(r'^designation_report$', views.designation_report, name='designation_report'),
    url(r'^employee_report$', views.employee_report, name='employee_report'),
    url(r'^salary_report$', views.salary_report, name='salary_report'),
    url(r'^salaryedit/(?P<x>\d+)/(?P<y>\d+)$', views.salaryedit, name='salaryedit'),

    url(r'^admin_account$', views.admin_account_info, name='admin_account'),
    url(r'^admin_salary$', views.admin_salary, name='admin_salary'),
    url(r'^admin_view_details$', views.admin_view_details, name='admin_view_details'),
    url(r'^admin_admin_salary$', views.admin_admin_salary, name='admin_admin_salary'),
    url(r'^delete/(?P<x>\d+)/$', views.delete, name='delete'),
    url(r'^view_salary_admin/(?P<x>\d+)/$', views.view_salary_admin, name='view_salary_admin'),
    url(r'^delete_admin/(?P<x>\d+)/$', views.delete_admin, name='delete_admin'),
    url(r'^salary_delete/(?P<x>\d+)/$', views.salary_delete, name='salary_delete'),
    url(r'^delete_salary_admin/(?P<x>\d+)/$', views.delete_salary_admin, name='delete_salary_admin'),
    url(r'^delete_department/(?P<x>\d+)/$', views.delete_department, name='delete_department'),
    url(r'^delete_designation/(?P<x>\d+)/$', views.delete_designation, name='delete_designation'),
    url(r'^delete_emp/(?P<x>\d+)/$', views.delete_emp, name='delete_emp'),
    # url(r'^edit_admin/(?P<x>\d+)/$', views.edit_admin,name='edit_admin'),

]

kamlesh_friend/travel/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index')
    # url(r'^about$', views.about, name='abouturl'),
    # url(r'^details$', views.details, name='module_details'),
    # url(r'^contact$', views.contact, name='contact_me'),
    # url(r'^loginme/$', views.log_in, name='loginme'),
    # # url(r'^login/$', auth_views.login, {'template_name': 'homepage/log_in_employee.html'}, name='login'),
    # url(r'^signup$', views.sign_up, name='signupme'),
]

kamlesh_friend/homepage/models.py
from django.db import models
from passlib.hash import pbkdf2_sha256


class contactus(models.Model):
    name = models.CharField(max_length=30)
    email = models.CharField(max_length=40)
    mobile = models.IntegerField()
    subject = models.CharField(max_length=20)
    message = models.CharField(max_length=250)

    def __str__(self):
        return self.name


# Create your models here.
class Regis_db(models.Model):
    firstname = models.CharField(max_length=25)
    lastname = models.CharField(max_length=25)
    username = models.CharField(max_length=10)
    email = models.EmailField(max_length=30)
    password = models.CharField(max_length=12)

    def __str__(self):
        return self.username

    def verify_password(self, raw_password):
        return pbkdf2_sha256.verify(raw_password, self.password)

kamlesh_friend/homepage/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from passlib.hash import pbkdf2_sha256

from .models import contactus, Regis_db


def homepage(request):
    return render(request, 'homepage/home.html')


def about(request):
    return render(request, 'homepage/aboutme.html')


def details(request):
    return render(request, 'homepage/module_details.html')


# def contact(request):


# return render(request, 'homepage/contact.html')
def contact(request):
    if request.method == "POST":
        # print(1)
        # reg_form1 = contact_form(request.POST)
        # if reg_form1.is_valid():
        #     print(1)
        #     username = reg_form1.cleaned_data.get('name')
        #     email = reg_form1.cleaned_data.get('email')
        #     mobile = reg_form1.cleaned_data.get('mobile')
        #     subject= reg_form1.cleaned_data.get('subject')
        #     message= reg_form1.cleaned_data.get('message')
        username = request.POST['name']

        email = request.POST['email']
        mobile = request.POST['mobile']
        subject = request.POST['subject']
        message = request.POST['message']
        reg_db_obj = contactus()
        reg_db_obj.name = username
        reg_db_obj.email = email
        reg_db_obj.mobile = mobile
        reg_db_obj.subject = subject
        reg_db_obj.message = message
        reg_db_obj.save()
        return redirect('homepageurl:homepage')
    return render(request, 'homepage/contact.html')

def log_in(request):
    if 'u' in request.session:
        u = request.session['u']

        return redirect('empurl:employee')


    elif request.method == 'POST':

        u = request.POST["username"]
        p = request.POST["password"]
        obj = len(Regis_db.objects.filter(password=p))

        if (len(Regis_db.objects.filter(username=u)) and obj):
            request.session['u'] = u

            return render(request, 'employee/emp.html')
        else:
            messages.warning(request, 'username or password wrong')

    return render(request, 'homepage/log_in_employee.html')


def sign_up(request):
    if request.method == "POST":
        firstname = request.POST['firstname']
        lastname = request.POST['lastname']
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        # enc_pass = pbkdf2_sha256.encrypt(password, rounds=12000, salt_size=32)
        password_confirm = request.POST['password_confirm']
        reg_db_obj = Regis_db()
        reg_db_obj.firstname = firstname
        reg_db_obj.lastname = lastname
        reg_db_obj.username = username
        reg_db_obj.email = email
        reg_db_obj.password = password
        reg_db_obj.password_confirm = password_confirm
        print(3)

        if (Regis_db.objects.filter(username=username).exists()):
            messages.warning(request, 'username or email already exist')
            return render(request, 'homepage/register.html')

        elif (Regis_db.objects.filter(email=email).exists()):
            print(2)
            messages.warning(request, 'username or email already exist')
            return render(request, 'homepage/register.html')
        else:

            reg_db_obj.save()

            return redirect('homepageurl:loginme')
    return render(request, 'homepage/register.html')

kamlesh_friend/homepage/templates/homepage/aboutme.html
{% load static %}
<!--<link rel="stylesheet" type="text/css" href="{% static 'homepage/style.css' %}"/>-->
<link rel="stylesheet" type="text/css" href="{% static 'homepage/animate.css' %}"/>
<link rel="stylesheet" type="text/css" href="{% static 'homepage/homepage.css' %}"/>


<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>About</title>
</head>
<body>


<nav class="navbar navbar-expand-lg navbar-light bg-light ">
    <a class="navbar-brand" href="{% url 'homepageurl:homepage' %}"> <img class="img-fluid"
                                                                          src="{% static 'homepage/images/logo.png' %}"
                                                                          alt="My image"
                                                                          style="width:20px"/>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'homepageurl:homepage' %}"><img
                        src="{% static 'homepage/images/homepage1.png' %}">Home <span
                        class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepageurl:abouturl' %}"><img
                        src="{% static 'homepage/images/about1.png' %}">About</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Login
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'payrollurl:payroll_login' %}"><img
                            src="{% static 'homepage/images/login.png' %}">Admin Login</a>
                    <a class="dropdown-item" href="{% url 'homepageurl:loginme' %}"><img
                            src="{% static 'homepage/images/login.png' %}">Employee Login</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepageurl:contact_me' %}"><img
                        src="{% static 'homepage/images/contact.png' %}">Contact Us</a>
            </li>

            <li class="nav-item">
                <a class="nav-link disabled" href="#"></a>
            </li>
        </ul>
        <span class="navbar-text">
    <b><i class="animated hinge" style="color:SlateBlue;font-family:verdana;font-size:120%;"><img class="animated hinge"
                                                                                                  src="{% static 'homepage/images/logo4.png' %}">Payroll Management System</i></b>
  </span>

    </div>
</nav>
{% block body %}
<div class="container-fluid" style="background-color:#64677F;height:60px">
    <div class="col-sm-4">
        <h3 class="animated bounceInLeft" align="center" style="color:white;hight:40px;padding-top:10px">About</h3>


    </div>
</div>

<div class="container" style="padding-top:90px">
    <div class="row">

        <div class="col-sm-6" style="padding-left:40px">
            <img class="rounded-circle animated bounceInLeft" style="float:right;"
                 src="{% static 'homepage/images/about_logo.jpg' %}"
                 width="500" height="400px">


        </div>
        <div class="col-sm-6">

            <h1 class="animated bounceInRight" style="font-size:25px;color:gray;" class="Monospace">
                About Payroll Management System
            </h1>
            <hr>
            <p class="animated bounceInRight" style="font-size:15px;color:#8D88A2">Payroll Management Sysytem is an
                important activity in any
                organization. The main objective of this project Pyaroll Manangement Sysytem is to managing employee's
                information of organization or for a small group. It has to store all the records of every employee
                within the organization to assign work to person and right salary and perks to their
                eligible emplooyees .It can also manage employee information efficiently, define the emoluments,
                deductions,leave, tax etc, generate pay slip, generate
                and manage the payrolls processes according to the salary structure assigned to the employee, etc. It
                keeps a track of the employees attendance and so on that basis it generate the monthly salary. </p>

            <img class="animated bounceInRight" style="padding-left:70px;float:left;"
                 src="{% static 'homepage/images/pic.gif' %}" width="400"
                 height="250px">

        </div>

    </div>
</div>
{% endblock %}
<hr>
<footer>
    <div class="row">
        <div class="col-sm-6">
            <<b class="animated bounceInLeft" style="font-size:18px;color:#F2F1F7">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CONTACT
            INFO:</b>&nbsp;
            <p class="animated bounceInLeft" style="font-size:14px;color:#F2F1F7">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img
                    src="{% static 'homepage/images/add1.png' %}">&nbsp;Address:New Ashok Nagar,Delhi</p>
            <p class="animated bounceInLeft" style="font-size:14px;color:#F2F1F7">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img
                    src="{% static 'homepage/images/city.png' %}">&nbsp;Main City:Delhi</p>
            <p class="animated bounceInLeft" style="font-size:14px;color:#F2F1F7">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img
                    src="{% static 'homepage/images/mobile.png' %}">&nbsp;Mobile No:9639830975</p>
            <p class="animated bounceInLeft" style="font-size:14px;color:#F2F1F7">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img
                    src="{% static 'homepage/images/phon.png' %}">&nbsp;Phon No:0122-2362458</p>
            <p class="animated bounceInLeft" style="font-size:14px;color:#F2F1F7">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img
                    src="{% static 'homepage/images/email3.png' %}">&nbsp;Email: <a style="color:white"
                                                                                    href="mailto:deegariya007@gmail.com">deegariya007@gmail.com</a>
            </p>
        </div>
        <div class="col-sm-6">
            <div id="map" style="width:200pxheight:250pxpx"></div>

            <script>
function myMap() {
  var mapCanvas = document.getElementById("map");
  var myCenter = new google.maps.LatLng(28.5911307,77.3078392);
  var mapOptions = {center: myCenter, zoom: 5};
  var map = new google.maps.Map(mapCanvas,mapOptions);
  var marker = new google.maps.Marker({
    position: myCenter,
    animation: google.maps.Animation.BOUNCE
  });
  marker.setMap(map);
}







            </script>

            <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA8PG7PfjhaZVR6EEbEy4c95CHOdNTmjw4&callback=myMap"></script>
        </div>
    </div>

</footer>
<footer style="background-color:black">
    <div class="row">


        <div class="col-sm-3">
            <p style="color:white;font-size:12px;padding-top:5px;padding-left:5px;">Major Project:MCA © 2018 All Rights
                Reserved.

            </p>
        </div>
        <div class="col-sm-3">
            <ul style="list-style-type:none">
                <li style="float:left;padding-top:7px">
                    <p style="color:white;font-size:12px">Follow me on:</p>
                </li>
                <li style="float:left">
                    <a href="https://www.facebook.com/deepak.gariya"> <img src="{% static 'homepage/images/fb1.png' %}"
                                                                           style="hight:27px;width:27px;padding-top:5px;padding-left:5px"></a>

                </li>
                <li style="float:left">
                    <a href="https://twitter.com/Deepakgariya1"> <img src="{% static 'homepage/images/twitter.png' %}"
                                                                      style="hight:27px;width:27px;padding-top:5px;padding-left:5px"></a>

                </li>
                <li style="float:left">
                    <a href="https://www.linkedin.com/in/deepak-gariya-3ab5b495
"><img src="{% static 'homepage/images/linkedin.png' %}"
       style="hight:27px;width:27px;padding-top:5px;padding-left:5px"></a>

                </li>


            </ul>
        </div>

    </div>
</footer>

</body>
</html>

kamlesh_friend/homepage/templates/homepage/contact.html
{% extends 'homepage/home.html'%}
{% load static %}


<title>{% block title %}Contact{% endblock %}</title>


<!--<<link rel="stylesheet" type="text/css" href="{% static 'homepage/contact.css' %}"/>
<script src="{% static 'homepage/contact.js' %}" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="{% static 'homepage/style.css' %}"/>
<div class="container">


    <div align="center">

        <div class="form-area" style="padding:top:100px;">
            <form role="form" style="align:center;" method="POST">
                {% csrf_token %}
                <br style="clear:both">
                <h3 style="margin-bottom: 25px; text-align: center;">Contact Us</h3>
                <div class="form-group">
                    <input type="text" class="form-control" id="name" name="name" placeholder="Name" required>
                </div>
                <div class="form-group">
                    <input type="email" class="form-control" id="email" name="email" placeholder="Email"
                           required>
                </div>
                <div class="form-group">
                    <input type="text" pattern="[1-9]{1}[0-9]{9}" class="form-control" id="mobile" name="mobile"
                           maxlength="10"
                           placeholder="Mobile Number"
                           required>
                </div>
                <div class="form-group">
                    <input type="text" class="form-control" id="subject" name="subject" placeholder="Subject"
                           required>
                </div>
                <div class="form-group">
                    <textarea class="form-control" type="textarea" name="message" id="message" placeholder="Message"
                              maxlength="250"
                              rows="7"></textarea>
                    <span class="help-block"><p id="characterLeft" class="help-block "></p></span>
                </div>

                <button class="btn btn-success">Submit</button>

            </form>
        </div>
    </div>
</div>-->
{%block body%}
<script src="{% static 'homepage/contact.js' %}"></script>

<link rel="stylesheet" type="text/css" href="{% static 'homepage/signup.css' %}"/>
<br>
<br>
<br>

<div class="container-fluid" style="background-color:#64677F;height:60px">
    <div class="col-sm-4">
        <h3 class="animated bounceInLeft" align="center" style="color:white;hight:40px;padding-top:10px">CONTACT US</h3>
    </div>

    <br>
    <br>
    <br>
    <br>
</div>
<br>
<div class="container">
    <div align="center">


        <div class="card" style="width:600px">
            <div class="bg-dark text-white card-header">CONTACT US HERE</div>
            <div class="card-body">
                <form id="sign_up" name="myform" method="post">
                    {%csrf_token%}

                    <div class="form-group">
                        <input id="name" name="name" class="form-control" type="text"
                               data-validation="required" placeholder="Username">

                        <span id="error_lastname1" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input id="email" name="email" class="form-control" type="email"
                               data-validation="required" placeholder="Email">
                        <span id="error_lastname2" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input pattern="[1-9]{1}[0-9]{9}" id="mobile" name="mobile" class="form-control" type="text"
                               data-validation="required" placeholder="Mobile Number" maxlength="10">
                        <span id="error_lastname3" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input id="subject" name="subject" class="form-control" type="text"
                               data-validation="required" placeholder="Subject">
                        <span id="error_lastname4" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <textarea class="form-control" type="textarea" name="message" id="message"
                                  placeholder="Message"
                                  maxlength="250"
                                  rows="7"></textarea>
                        <span class="help-block"><p id="characterLeft" class="help-block "></p></span></div>

                    <button id="submit" type="submit" value="submit" class="btn btn-dark">Submit</button>

                </form>


            </div>
            <div class="bg-dark text-white card-footer">

            </div>

        </div>

    </div>
</div>

<br>
<br>
<br>
<br>

{%endblock%}

kamlesh_friend/homepage/templates/homepage/log_in_employee.html
{% extends 'homepage/home.html'%}
{% load static %}

<title>{% block title %}Login{% endblock %}</title>
{%block body%}
<link rel="stylesheet" type="text/css" href="{% static 'homepage/login.css' %}"/>
<script src="{% static 'homepage/login.js' %}" type="text/javascript"></script>

<body>

<br>
<br>
<br>

<div class="container-fluid" style="background-color:#64677F;height:60px">
    <div class="col-sm-4">
        <h3 class="animated bounceInLeft" align="center" style="color:white;hight:40px;padding-top:10px">EMPLOYEE
            LOGIN</h3>


    </div>
</div>
<br>
<br>
<br>
<br>

<div class="container">
    <div align="center">

        <div class="card" style="width:500px">
            <div class="bg-dark text-white card-header">LOGIN TO YOUR ACCOUNT</div>
            <div class="card-body">
                {% if username is None %}
                <form name="myform" method="post">
                    {%csrf_token%}

                    <div class="form-group">

                        <input id="username" name="username" class="form-control" type="text"
                               data-validation="required" placeholder="Username">
                        <span id="error_name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input id="password" name="password" class="form-control" type="password"
                               data-validation="required" placeholder="Password">
                        <span id="error_lastname" class="text-danger"></span>
                    </div>
                    <button id="submit" type="submit" value="submit" onclick="validate()" class="btn btn-dark">Login
                    </button>
                    {% if messages %}

                    {% for message in messages %}
                    <div class="alert alert-warning alert-dismissible {{ message.tags }}">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <strong>{{message}}</strong>
                    </div>
                    {%endfor%}


                    {% endif %}
                </form>
                {% endif %}
                <div class="row">
                    <div class="col-sm-6">
                        <a href="{%url 'password_reset'%}">Forgot Password?</a>

                    </div>
                    <div class="col-sm-6">
                        <p>need account? <a href="{% url 'homepageurl:signupme' %}">Sign up Here!</a></p>

                    </div>


                </div>

            </div>
            <div class="bg-dark text-white card-footer"></div>
        </div>
    </div>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
</body>
{%endblock%}

kamlesh_friend/homepage/templates/homepage/module_details.html
{% extends 'homepage/home.html'%}
{% block body %}
<style>

    h2{
     text-decoration: underline;
     text-transform: capitalize;
     text-indent: 10px;

    p{
    text-indent: 70px;

    }
    ul.a {
    list-style-type: circle;
}










</style>

<div class="container-fluid" style="background-color:#64677F;height:60px">
    <div class="col-sm-4">
        <h3 align="center" style="color:white;hight:40px;padding-top:10px">Module Details</h3>


    </div>
</div>
<br>
<div class="container">
    <h2 style="font-size:25px;color:gray;">
        This project is divided into three Module
    </h2>
    <br>
    <br>

    <h6>1.Manage The Employees Payroll</h6>
    <p>


        This module helps to maintain emloyees pay slips, pay sheets, pay summaries, salary advancement’s, over time
        calculation’s, no pay deduction, payee tax report, OT, no
        pay detailed report, late minutes deduction report, signature sheets, loan maintenance, salary pay to
        bank.
    </p>
    <ul class="a">
        <li>Manage every Employees Salary</li>
        <li>Define every employees emoluments,deductions,tax</li>
        <li>Manage the Payroll processes</li>
    </ul>
    <h6>2.Leave and Vacation Management</h6>
    <p>
        This module helps to keep track of all the employees leave deatils,work hour and mainatain the employees salary
        based on their leaves.
    </p>
    <ul class="a">
        <li>Manage every Employees Leave application</li>
        <li>Keeps a track of employees attendance and on that basis it genrates the montholy salary</li>
        <li>Paperless work</li>
    </ul>
    <h6>3.Employees Management System</h6>
    <p>
        This module keeps track of all the employees personal information, details of department, and assign the work
        for every employees.


    </p>
    <ul class="a">
        <li>Manage every Employees Personal details, departments</li>
        <li>Assign the work and salary for every employees</li>
        <li>Easy way to organise all the employees departments and personal details</li>
    </ul>

</div>


{% endblock %}