HNMS/HNMS/HealthNet-master/HAccelerator/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^HealthNet/', include('HealthNet.urls')),
    url(r'^admin/', admin.site.urls),
]

admin.site.site_header = 'HealthNet R2'

HNMS/HNMS/HealthNet-master/HealthNet/urls.py
# File: urls.py
# Description: This file contains the Django url statements.
# Author(s): Rahul Suites (1)

# imports
from django.conf.urls import url
from . import views

# url statements
app_name = 'HealthNet'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^register/$', views.registerP, name='registerP'),
    url(r'^register/create$', views.createPLogIn, name='createPLogIn'),
    url(r'^password/$', views.password, name='password'),
    url(r'^password/changepass/$', views.changePass, name='changepass'),
    url(r'^verify/$', views.verify, name='verify'),
    url(r'^home/$', views.home, name='home'),
    url(r'^home/registerDN$', views.registerDN, name='registerDN'),
    url(r'^home/registerDN/createDN$', views.createDNLogIn, name='createDNLogIn'),
    url(r'^information/$', views.information, name='information'),
    url(r'^information/updatePro$', views.updatePro, name='updatePro'),
    url(r'^information/updatePro/updateProInfo$', views.updateProInfo, name='updateProInfo'),
    url(r'^information/updateMed/(?P<pat_id>[0-9]+)/', views.updateMed, name='updateMed'),
    url(r'^information/updateMed/updateMedInfo/(?P<pat_id>[0-9]+)/', views.updateMedInfo, name='updateMedInfo'),
    url(r'^information/export$', views.export, name='export'),
    url(r'^information/tests/(?P<pat_id>[0-9]+)/', views.tests, name='tests'),
    url(r'^information/tests/createTest/(?P<pat_id>[0-9]+)/', views.createTest, name='createTest'),
    url(r'^information/tests/createTest/createTestInfo/(?P<pat_id>[0-9]+)/', views.createTestInfo, name='createTestInfo'),
    url(r'^information/tests/releaseTest/(?P<test_id>[0-9]+)/', views.releaseTest, name='releaseTest'),
    url(r'^information/testDetails/(?P<test_id>[0-9]+)/', views.testDetails, name='testDetails'),
    url(r'^information/discharge/(?P<pat_id>[0-9]+)/', views.discharge, name='discharge'),
    url(r'^information/admission/(?P<pat_id>[0-9]+)/(?P<emp_id>[0-9]+)/', views.admission, name='admission'),
    url(r'^information/transfer/(?P<pat_id>[0-9]+)/(?P<emp_id>[0-9]+)/', views.transfer, name='transfer'),
    url(r'^appointments/$', views.appointments, name='appointments'),
    url(r'^appointments/createAppt$', views.createAppt, name='createAppt'),
    url(r'^appointments/createAppt/createApptInfo$', views.createApptInfo, name="createApptInfo"),
    url(r'^appointments/updateAppt/(?P<appt_id>[0-9]+)/', views.updateAppt, name='updateAppt'),
    url(r'^appointments/updateAppt/updateApptInfo/(?P<appt_id>[0-9]+)/', views.updateApptInfo, name='updateApptInfo'),
    url(r'^appointments/cancelAppt/(?P<appt_id>[0-9]+)/', views.cancelAppt, name='cancelAppt'),
    url(r'^prescriptions/$', views.prescriptions, name='prescriptions'),
    url(r'^prescriptions/createPres$', views.createPres, name='createPres'),
    url(r'^prescriptions/createPres/createPresInfo$', views.createPresInfo, name="createPresInfo"),
    url(r'^prescriptions/updatePres/(?P<pres_id>[0-9]+)/', views.updatePres, name='updatePres'),
    url(r'^prescriptions/updatePres/updatePresInfo/(?P<pres_id>[0-9]+)/', views.updatePresInfo, name='updatePresInfo'),
    url(r'^prescriptions/removePres/(?P<pres_id>[0-9]+)/', views.removePres, name='removePres'),
    url(r'^about/$', views.about, name='about'),
    url(r'^messages/$', views.messages, name='messages'),
    url(r'^messages/createMess/$', views.createMess, name='createMess'),
    url(r'^messages/createMess/createMessInfo/(?P<mess_id>-1)/', views.createMessInfo, name="createMessInfo"),
    url(r'^messages/replyMess/(?P<mess_id>[0-9]+)/', views.replyMess, name='replyMess'),
    url(r'^messages/replyMess/createMessInfo/(?P<mess_id>[0-9]+)/', views.createMessInfo, name="createMessInfo"),
    url(r'^messages/viewMess/(?P<mess_id>[0-9]+)/', views.viewMess, name='viewMess'),
    url(r'^messages/deleteMess/(?P<mess_id>[0-9]+)/', views.deleteMess, name='deleteMess'),
    url(r'^log/$', views.log, name='log'),
    url(r'^statistics/$', views.statistics, name='statistics'),
    url(r'^logOut/$', views.logOut, name='logOut')
]

HNMS/HNMS/HealthNet-master/HealthNet/views.py
# File: views.py
# Description: This file contains Python and Django code which will form the
#              Controller element of the Model-Template-Controller (MTC) design
#              pattern.

# imports
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from .models import Test
from .models import Patient
from .models import EmergencyContact
from .models import Doctor
from .models import Nurse
from .models import Prescription
from .models import Hospital
from .models import Appointment
from .models import LogInInfo
from .models import Administrator
from .models import Message
from django.core.exceptions import ObjectDoesNotExist
from django.utils.datastructures import MultiValueDictKeyError
import datetime
from datetime import date
import os
import csv

# This variable is for storing the username entered when a user logs-in
uname = ''


# This module handles the logging of activities by saving logs to a plaintext file which is then rendered
# in HTML for administrators to view.
def logActivity(activity):
    filename = "log.txt"
    cwd = os.getcwd()
    target = open(cwd + "\\HealthNet\\log\\" + filename, 'a')
    target.write(activity)
    target.write("\n")
    target.close()


# This module handles the generic template view for the index page in which users will log-in or register
# if they have not made credentials.
class IndexView(generic.ListView):
    template_name = 'HealthNet/index.html'
    context_object_name = 'user_login_information'

    def get_queryset(self):
        return LogInInfo.objects.order_by('-username')


# This module simply renders the HTML page for the registration screen.
def registerP(request):
    return render(request, 'HealthNet/registerP.html')


# This module handles the user registration. The "LogInInfo" object is used to store their credentials in the database.
def createPLogIn(request):
    firstName = (request.POST['firstName'])
    lastName = (request.POST['lastName'])
    address = (request.POST['address'])
    number = (request.POST['number'])
    email = (request.POST['email'])
    provider = (request.POST['provider'])
    insuranceid = (request.POST['insuranceid'])
    contactfname = (request.POST['contactfname'])
    contactlname = (request.POST['contactlname'])
    contactaddress = (request.POST['contactaddress'])
    contactnumber = (request.POST['contactnumber'])
    height = (request.POST['height'])
    weight = (request.POST['weight'])
    allergies = (request.POST['allergies'])
    gender = (request.POST['gender'])
    username = (request.POST['username'])
    password = (request.POST['password'])
    try:
        logininfo = LogInInfo.objects.get(username=username)
    except ObjectDoesNotExist:
        LogInInfo.objects.create(username=username, password=password)
        global uname
        uname = username
        try:
            contact = EmergencyContact.objects.get(firstName=contactfname, lastName=contactlname,
                                                      address=contactaddress, number=contactnumber)
        except ObjectDoesNotExist:
            contact = EmergencyContact.objects.create(firstName=contactfname, lastName=contactlname,
                                                      address=contactaddress, number=contactnumber)
        Patient.objects.create(username=uname)
        patient = Patient.objects.get(username=uname)
        patient.firstName = firstName
        patient.lastName = lastName
        patient.address = address
        patient.number = number
        patient.email = email
        patient.provider = provider
        patient.insuranceid = insuranceid
        patient.contact = contact
        patient.height = height
        patient.weight = weight
        patient.allergies = allergies
        patient.gender = gender
        patient.save()

        activity = "User " + username + " registered a new account - logged on: " +\
                   datetime.datetime.now().strftime('%m/%d/%y @ %H:%M:%S')
        logActivity(activity)
        return HttpResponseRedirect(reverse('HealthNet:home', args=()))
    else:
        return render(request, 'HealthNet/registerP.html', {
            'username': username,
            'error_message': "Username already exists.",
        })


# This module simply renders the HTML page for the password change screen.
def password(request):
    return render(request, 'HealthNet/password.html')


# This module handles the changing of a user's password
def changePass(request):
    try:
        username = (request.POST["username"])
        newpass = (request.POST["password"])
        currinfo = LogInInfo.objects.get(username=username)
    except LogInInfo.DoesNotExist:
        return render(request, 'HealthNet/password.html', {
            'username': username,
            'error_message': "There was a problem with your username.",
            })
    else:
        currinfo.password = newpass
        currinfo.save()
        activity = "User " + username + " changed their password - logged on: " +\
                   datetime.datetime.now().strftime('%m/%d/%y @ %H:%M:%S')
        logActivity(activity)
        return HttpResponseRedirect(reverse('HealthNet:index', args=()))


# This module handles the attempt of a user to log-in to their profile. If the username and password are valid,
# the user is redirected to their profile. If not, an error message is generated and the user is
# redirected to the index page.
def verify(request):
    username = (request.POST['username'])
    passwordInput = (request.POST['password'])
    try:
        current = LogInInfo.objects.get(username=username)
    except LogInInfo.DoesNotExist:
        return render(request, 'HealthNet/index.html', {
            'username': username,
            'error_message': "There was a problem with your username.",
        })
    else:
        passwordActual = current.password
        if passwordInput == passwordActual:
            global uname
            uname = username
            activity = "User " + username + " logged in - logged on: " + datetime.datetime.now().strftime('%m/%d/%y @ %H:%M:%S')
            logActivity(activity)
            return HttpResponseRedirect(reverse('HealthNet:home', args=()))
        else:
            return render(request, 'HealthNet/index.html', {
                'username': username,
                'error_message': "There was a problem with your password.",
            })


# This module simply renders the home page for a user
def home(request):
    try:
        p = Patient.objects.get(username=uname)
    except Patient.DoesNotExist:
        try:
            d = Doctor.objects.get(username=uname)
        except Doctor.DoesNotExist:
            try:
                n = Nurse.objects.get(username=uname)
            except Nurse.DoesNotExist:
                try:
                    a = Administrator.objects.get(username=uname)
                except Administrator.DoesNotExist:
                    return render(request, 'HealthNet/index.html', {
                        'error_message': "An error has occurred"
                        })
                else:
                    utype = "Administrator"
                    context = {'user': a,
                               'type': utype}
                    return render(request, 'HealthNet/home.html', context)
            else:
                utype = "Nurse"
                context = {'user': n,
                           'type': utype}
                return render(request, 'HealthNet/home.html', context)
        else:
            utype = "Doctor"
            context = {'user': d,
                       'type': utype}
            return render(request, 'HealthNet/home.html', context)
    else:
        utype = "Patient"
        context = {'user': p,
                   'type': utype}
        return render(request, 'HealthNet/home.html', context)


# This module simply renders the HTML page for the doctor and nurse registration screen.
def registerDN(request):
    workplaces = Hospital.objects.order_by("-name")
    admin = Administrator.objects.get(username=uname)
    context = {'workplaces': workplaces,
               'admin': admin}
    return render(request, 'HealthNet/registerDN.html', context)


# This module handles the doctor and nurse registration. The "LogInInfo" object is used to store their credentials
# in the database.
def createDNLogIn(request):
    firstName = (request.POST['firstName'])
    lastName = (request.POST['lastName'])
    type = (request.POST['type'])
    username = (request.POST['username'])
    password = (request.POST['password'])
    admin = Administrator.objects.get(username=uname)
    try:
        logininfo = LogInInfo.objects.get(username=username)
    except ObjectDoesNotExist:
        LogInInfo.objects.create(username=username, password=password)
        if type == "Doctor":
            Doctor.objects.create(username=username, firstName=firstName, lastName=lastName)
            d = Doctor.objects.get(username=username)
            d.workplace = admin.workplace
            d.save()
            activity = "Administrator " + uname + " registered a new doctor account - logged on: " + \
                       datetime.datetime.now().strftime('%m/%d/%y @ %H:%M:%S')
            logActivity(activity)
            return HttpResponseRedirect(reverse('HealthNet:home', args=()))
        elif type == "Nurse":
            Nurse.objects.create(username=username,  firstName=firstName, lastName=lastName)
            n = Nurse.objects.get(username=username)
            n.workplace = admin.workplace
            n.save()
            activity = "Administrator " + uname + " registered a new nurse account - logged on: " + \
                       datetime.datetime.now().strftime('%m/%d/%y @ %H:%M:%S')
            logActivity(activity)
            return HttpResponseRedirect(reverse('HealthNet:home', args=()))

HNMS/HNMS/HealthNet-master/HealthNet/templates/HealthNet/information.html
<!DOCTYPE html>
<html>

{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'HAccelerator/mainPages.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'HAccelerator/animate.css' %}" />
<link rel='shortcut icon' href="{% static 'HAccelerator/images/favicon.ico' %}" type='images/favicon' />

<head>
	<title>HealthNet | User Information</title>

    <script>
    function conExport()
    {
        if (confirm("WARNING: Rawat's HeathNet  cannot be held responsible if your exported " +
                        "information falls into the wrong hands. Are you sure you want to continue?"))
        {
            return true;
        }
        else
        {
            return false;
        }
    }
    </script>
</head>

<ul class="nav">
	<li class="nav_container"><a class="nav_items" href="{% url 'HealthNet:home' %}">Home</a></li>
	<li class="nav_container"><a class="nav_item_active" href="{% url 'HealthNet:information' %}">User Information</a></li>
	<li class="nav_container"><a class="nav_items" href="{% url 'HealthNet:appointments' %}">Manage Appointments</a></li>
    <li class="nav_container"><a class="nav_items" href="{% url 'HealthNet:prescriptions' %}">Prescriptions</a></li>
	<li class="nav_container"><a class="nav_items" href="{% url 'HealthNet:about' %}">About</a></li>
	<li class="nav_container"><a class="nav_items" href="{% url 'HealthNet:messages' %}">Messages</a></li>
	<li style="float:right" class="nav_container"><a class="nav_items" href="{% url 'HealthNet:logOut' %}">Log Out</a></li>
</ul>

<body style="background-color:#D7DBDD;">
    <div id="container">
        <div id="tablecontainer">
            {% if type == "Patient" %}
                <h2  class="animated shake">Profile Information</h2>
                <table>
                    <tr>
                        <th>Name</th>
                        <th>Address</th>
                        <th>Phone Number</th>
                        <th>Email</th>
                        <th>Insurance Provider</th>
                        <th>Insurance ID</th>
                    </tr>
                    <tr>
                        <td>{{ patient.lastName }}, {{ patient.firstName }}</td>
                        <td>{{ patient.address }}</td>
                        <td>{{ patient.number }}</td>
                        <td>{{ patient.email }}</td>
                        <td>{{ patient.provider }}</td>
                        <td>{{ patient.insuranceid }}</td>
                    </tr>
                </table>

                <h2 class="animated shake">Emergency Contact</h2>
                <table>
                    <tr>
                        <th>Name</th>
                        <th>Address</th>
                        <th>Phone Number</th>
                    </tr>
                    <tr>
                        <td>{{ patient.contact.lastName }}, {{ patient.contact.firstName }}</td>
                        <td>{{ patient.contact.address }}</td>
                        <td>{{ patient.contact.number }}</td>
                    </tr>
                </table>

                <br>

                <form action="{% url 'HealthNet:updatePro' %}">
                    <input class="animated shake" class="animated shake" type="submit" value="Update Profile Information" />
                </form>

                <br>
                <br>

                <h2 class="animated shake">Medical Information</h2>
                <table>
                    <tr>
                        <th>Height</th>
                        <th>Weight</th>
                        <th>Allergies</th>
                        <th>Gender</th>
                    </tr>
                    <tr>
                        <td>{{ patient.height }}</td>
                        <td>{{ patient.weight }} lbs</td>
                        <td>{{ patient.allergies }}</td>
                        <td>{{ patient.gender }}</td>
                    </tr>
                </table>

                <br>
                <br>

                <h2 class="animated shake">Test Results</h2>
                {% if tests %}
                    <table>
                        <tr>
                            <th>Test Name</th>
                            <th>Release Status</th>
                        </tr>
                        {% for t in tests %}
                            <tr>
                                {% if t.released == True %}
                                    <td><a class="alink" href="{% url 'HealthNet:testDetails' t.id %}">{{ t.name }}</a></td>
                                {% else %}
                                    <td>{{ t.name }}</td>
                                {% endif %}
                                {% if t.released == True %}
                                    <td>Test is Released</td>
                                {% else %}
                                    <td>Not yet Released</td>
                                {% endif %}
                                </tr>
                        {% endfor %}
                    </table>
                {% else %}
                    <p class="animated shake" >There are no tests to view</p>
                {% endif %}

                <br>

				<form action="{% url 'HealthNet:export' %}" onsubmit="return conExport();">
                    <input class="animated shake" class="button" type="submit" value="Export Tests and Profile Information" />
                </form>
			{% endif %}
			
			{% if type != "Patient" %}
                <h2 class="animated shake" ><span style="text-decoration: underline;">{{ employee.firstName }} {{ employee.lastName }}</span>, these are the patients at <span style="text-decoration: underline;">{{ employee.workplace.name }}</span></h2>
                {% if patw %}
                    <table>
                        <tr>
                            <th>Patient Name</th>
                            <th>Height</th>
                            <th>Weight</th>
                            <th>Allergies</th>
                            <th>Gender</th>
                            {% if type == "Doctor" %}
                                <th></th>
                                <th></th>
                            {% endif %}
                        </tr>
                            {% for patient in patients %}
                                {% if patient.hospital == employee.workplace %}
                                    <tr>
                                        <td><a class="alink" href="{% url 'HealthNet:updateMed' patient.id %}">{{ patient.lastName }}, {{ patient.firstName }}</a></td>
                                        <td>{{ patient.height }}</td>
                                        <td>{{ patient.weight }} lbs</td>
                                        <td>{{ patient.allergies }}</td>
                                        <td>{{ patient.gender }}</td>
                                        {% if type == "Doctor" %}
                                            <td><form action="{% url 'HealthNet:tests' patient.id %}"><input type="submit" value="Test Results" /></form></td>
                                            <td><form action="{% url 'HealthNet:discharge' patient.id %}"><input type="submit" value="Discharge" /></form></td>
                                        {% endif %}
                                    </tr>
                                {% endif %}
                            {% endfor %}
                    </table>
                {% else %}
                    <p>There are no patients at your hospital</p>
                {% endif %}

                <br>
                <br>

                <h2 class="animated shake" >Non Admitted Patients</h2>
                <table>
                    <tr>
                        <th>Patient Name</th>
                        <th>Current Hospital</th>
                        <th></th>
                    </tr>
                    {% for patient in patients %}
                        {% if patient.hospital.address != employee.workplace.address %}
                            <tr>
                                {% if type == "Doctor" %}
                                    <td><a class="alink" href="{% url 'HealthNet:updateMed' patient.id %}">{{ patient.lastName }}, {{ patient.firstName }}</a></td>
                                {% else %}
                                    <td>{{ patient.lastName }}, {{ patient.firstName }}</td>
                                {% endif %}

                                {%if patient.hospital == None %}
                                    <td>{{ patient.hospital.name }}</td>
                                    <td><form action="{% url 'HealthNet:admission' patient.id employee.workplace.id%}"><input type="submit" value="Admit" /></form></td>
                                {% else %}
                                    {% if type == "Nurse" %}
                                        <td>{{ patient.hospital.name }}</td>
                                    {% endif %}
                                    {% if type == "Doctor" %}
                                        <td>{{ patient.hospital.name }}</td>
                                        <td><form action="{% url 'HealthNet:transfer' patient.id employee.workplace.id%}"><input type="submit" value="Transfer" /></form></td>
                                    {% endif %}
                                {% endif %}
                            </tr>
                        {% endif %}
                    {% endfor %}
                </table>
            {% endif %}
        </div>
    </div>
</body>
</html>

HNMS/HNMS/HealthNet-master/HealthNet/templates/HealthNet/log.html
<!DOCTYPE html>
<html>

{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'HAccelerator/formPages.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'HAccelerator/formPages.css' %}" />
<link rel='shortcut icon' href="{% static 'HAccelerator/images/favicon.ico' %}" type='images/favicon' />

<head>
    <title>HealthNet | Activity Log</title>
</head>

<body  style="background-color:#BFC9CA";>
    <div  style="width:700px;height:400px; margin:0 auto; " id="container">
        <h1>Activity Log</h1>
        {%for logItem in logString%}
            {{ logItem }}
            <br>
        {% endfor %}

        <form action="{% url 'HealthNet:home' %}">
            <input class="button" type="submit" value="Return" />
        </form>
    </div>
</body>
</html>

HNMS/HNMS/HealthNet-master/HealthNet/templates/HealthNet/messages.html
<!DOCTYPE html>
<html>

{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'HAccelerator/mainPages.css' %}" />
<link rel='shortcut icon' href="{% static 'HAccelerator/images/favicon.ico' %}" type='images/favicon' />
<link rel="stylesheet" type="text/css" href="{% static 'HAccelerator/animate.css' %}" />
<head>
	<title>HealthNet | Messages</title>


    <meta name="viewport" content="width=device-width, initial-scale=1">
<style>

body{

background-image: url('{% static "HAccelerator/images/hops13.jpeg" %}'); width=100%;
width:100%;height:100%;
    background-size:cover;
    background-repeat: no-repeat;
    background-position: top;
    background-attachment: fixed;
}

table {
    border-collapse: collapse;
    border-spacing: 0;
    width: 100%;
    border: 1px solid #ddd;
}

th, td {
    text-align: left;
    padding: 16px;
}

tr:nth-child(even) {
    background-color: #f2f2f2
}
</style>
</head>

<ul class="nav">
    {% if type == "Administrator"%}
		<li class="nav_container"><a class="nav_items" href="{% url 'HealthNet:home' %}">Home</a></li>
        <li class="nav_container"><a class="nav_items" href="{% url 'HealthNet:log' %}">Activity Log</a></li>
        <li class="nav_container"><a class="nav_items" href="{% url 'HealthNet:statistics' %}">Statistics</a></li>
        <li class="nav_container"><a class="nav_items" href="{% url 'HealthNet:registerDN' %}">Staff Registration</a></li>
		<li class="nav_container"><a class="nav_item_active" href="{% url 'HealthNet:messages' %}">Messages</a></li>
		<li style="float:right" class="nav_container"><a class="nav_items" href="{% url 'HealthNet:logOut' %}">Log Out</a></li>
    {% else %}
		<li class="nav_container"><a class="nav_items" href="{% url 'HealthNet:home' %}">Home</a></li>
        <li class="nav_container"><a class="nav_items" href="{% url 'HealthNet:information' %}">User Information</a></li>
        <li class="nav_container"><a class="nav_items" href="{% url 'HealthNet:appointments' %}">Manage Appointments</a></li>
        <li class="nav_container"><a class="nav_items" href="{% url 'HealthNet:prescriptions' %}">Prescriptions</a></li>
        <li class="nav_container"><a class="nav_items" href="{% url 'HealthNet:about' %}">About</a></li>
        <li class="nav_container"><a class="nav_item_active" href="{% url 'HealthNet:messages' %}">Messages</a></li>
        <li style="float:right" class="nav_container"><a class="nav_items" href="{% url 'HealthNet:logOut' %}">Log Out</a></li>
	{% endif %}
</ul>



<body>




<!--<style>-->
<!--h2-->
<!--{-->
    <!--color:red;-->
    <!--background-color:black;-->
    <!--}-->

    <!---->
<!--</sytle>-->
    <div id="container">
        <div id="tablecontainer">
            <h2 class="animated shake" style="color:blue; background-color:rgba(0,0,0,4);display:inline-block";> Inbox</h2>
            {% if messages %}
	            <table>
                    <tr>
                        <th>Sender Username</th>
						<th>Sender Type</th>
						<th>Date Sent</th>
                        <th>Subject</th>
						<th></th>
                    </tr>
                    {% for m in messages %}
                        <tr>
                            <td>{{ m.senderName }}</td>
							<td>{{ m.senderType }}</td>
                            <td>{{ m.date }}</td>
                            <td>{{ m.subjectLine }}</td>
                            <td><form action="{% url 'HealthNet:viewMess' m.id %}"><input type="submit" value="View" /></form></td>
                        </tr>
                    {% endfor %}
                </table>
            {% else %}
                <p class="animated shake">There are no messages to view</p>
            {% endif %}

            <br>

			<h2 class="animated shake" style="color:blue; background-color:rgba(0,0,0,4);display:inline-block;">Sent Messages</h2>
            {% if sendMessages %}
	            <table>
                    <tr>
                        <th>To</th>
						<th>Date Sent</th>
                        <th>Subject</th>
						<th></th>
                    </tr>
                    {% for m in sendMessages %}

                        <tr>
                            <td>{{ m.receiverName }}</td>
                            <td>{{ m.date }}</td>
                            <td>{{ m.subjectLine }}</td>
                            <td><form action="{% url 'HealthNet:viewMess' m.id %}"><input type="submit" value="View" /></form></td>
                        </tr>
                    {% endfor %}
                </table>
            {% else %}
                <p  class="animated shake">You have sent no messages</p>
            {% endif %}

            <br>

            <form action="{% url 'HealthNet:createMess' %}">
                <input class="animated flip" type="submit" value="Create Message" />
            </form>
        </div>
    </div>
</body>
</html>

HNMS/HNMS/HealthNet-master/HealthNet/templates/HealthNet/viewMess.html
<!DOCTYPE html>
<html>

{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'HAccelerator/formPages.css' %}" />
<link rel='shortcut icon' href="{% static 'HAccelerator/images/favicon.ico' %}" type='images/favicon' />

<head>
	<title>HealthNet | View Message</title>
</head>

<body style="background-color:#85929E  ;">

<div class="container">
    <div align="center">
        <div class="card" style="width:600px">
            <div class="bg-dark text-white card-header" style="width:600px;height:300px; margin:0 auto; background-color:#AAB7B8 ; " id="container">
        <div class="card-body">
                <div id="formContainer">
            <h1>Subject: {{ message.subjectLine }}</h1>
            <p><b>{{ message.message }}</b></p>
            <form action="{% url 'HealthNet:messages' %}">
                <input class="button" type="submit" value="Back" />
            </form>
           <form action="{% url 'HealthNet:deleteMess' message.id %}">
                <input class="button" type="submit" value="Delete" />
            </form>
			<form action="{% url 'HealthNet:replyMess' message.id %} %}">
                <input class="button" type="submit" value="Reply" />
            </form>
        </div>
    </div>
                </div>
          </div>
        </div>
    </div>
</body>
</html>