kamlesh_friend/employee/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from employee import views

urlpatterns = [
    url(r'^$', views.employee_details, name='employee'),
    url(r'^about$', views.about, name='abouturl'),
    url(r'^employee/details$', views.emp_details, name='emp_details'),
    url(r'^employee/salary/$', views.salary_detail, name='salary_details'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^view_details$', views.view_details, name='view_details'),
    url(r'^change_password$', views.change_password, name='change_password'),
    url(r'^view_salary/(?P<x>\d+)/$', views.view_salary, name='view_salary'),
    url(r'^delete_data/(?P<x>\d+)/$', views.delete_data, name='delete_data'),
]

kamlesh_friend/payroll/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [   url(' ', include('travel.urls',namespace='index')),
                  url(r'^admin/', admin.site.urls),

                  url(r'^', include('homepage.urls', namespace='homepageurl')),
                  url(r'^employee/', include('employee.urls', namespace='empurl')),
                  url(r'^payroll_admin/', include('payroll_admin.urls', namespace='payrollurl')),

                  url('^', include('django.contrib.auth.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kamlesh_friend/travel/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index')
    # url(r'^about$', views.about, name='abouturl'),
    # url(r'^details$', views.details, name='module_details'),
    # url(r'^contact$', views.contact, name='contact_me'),
    # url(r'^loginme/$', views.log_in, name='loginme'),
    # # url(r'^login/$', auth_views.login, {'template_name': 'homepage/log_in_employee.html'}, name='login'),
    # url(r'^signup$', views.sign_up, name='signupme'),
]

kamlesh_friend/employee/models.py
from django.db import models

from homepage.models import Regis_db


# Create your models here.
class emp_account(models.Model):
    user_name = models.OneToOneField(Regis_db, on_delete=models.CASCADE, primary_key=True)
    fullname = models.CharField(max_length=40)
    department = models.CharField(max_length=40)
    designation = models.CharField(max_length=40)
    DISPLAY_CHOICES = (
        ("male", "Male"),
        ("female", "Female")
    )

    gender = models.CharField(choices=DISPLAY_CHOICES, max_length=128)
    mobile = models.IntegerField()
    bday = models.DateField()
    add1 = models.CharField(max_length=120)
    email = models.EmailField(max_length=30)
    city = models.CharField(max_length=30)
    state = models.CharField(max_length=30)
    country = models.CharField(max_length=30)
    filename = models.ImageField(blank=True, null=True)
    account = models.IntegerField()
    bank = models.CharField(max_length=40)
    pfaccount = models.IntegerField()
    joining_date = models.DateField()

    def __str__(self):
        return self.fullname

kamlesh_friend/employee/views.py
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.shortcuts import render, redirect

from homepage.models import Regis_db
from payroll_admin.models import salary_details
from .models import emp_account


# Create your views here.


def employee_details(request):
    # u = None
    # if (request.method == "GET"):
    #
    #     if 'action' in request.GET:
    #         print(1)
    #         action = request.GET.get('action')
    #         if action == 'logout':
    #             if request.session.has_key('u'):
    #                 request.session.flush()
    #                 return render(request, 'homepage/log_in_employee.html')
    #                 # return HttpResponseRedirect('session')

    return render(request, 'employee/emp.html')


#

#
def change_password(request):
    if request.method == 'POST':
        print(1)
        password = request.POST['password']
        # enc_pass = pbkdf2_sha256.encrypt(password,rounds=12000,salt_size=32)

        s = Regis_db.objects.get(username=request.session['u'])

        s.password = password
        s.save()
        update_session_auth_hash(request, s)

        messages.success(request, 'Your password was successfully updated!')
        # return redirect('homepageurl:loginme')

    return render(request, 'employee/change_password.html')


def about(request):
    return render(request, 'employee/aboutme.html')


def emp_details(request):
    s = Regis_db.objects.filter(username=request.session['u'])

    if request.method == "POST":
        department = request.POST['department']
        designation = request.POST['designation']
        gender = request.POST['gender']
        fullname = request.POST['fullname']
        mobile = request.POST['mobile']
        bday = request.POST['bday']
        add1 = request.POST['add1']
        email = request.POST['email']
        add2 = request.POST['add2']
        city = request.POST['city']
        state = request.POST["state"]
        country = request.POST['country']
        account = request.POST['account']
        bank = request.POST['bank']
        pfaccount = request.POST['pfaccount']
        joining_date = request.POST['joining_date']

        emp_obj = emp_account(filename=request.FILES['filename'])
        emp_obj.department = department
        emp_obj.designation = designation
        emp_obj.gender = gender
        emp_obj.mobile = mobile
        emp_obj.add1 = add1
        emp_obj.bday = bday
        emp_obj.add2 = add2
        emp_obj.city = city
        emp_obj.fullname = fullname
        emp_obj.state = state
        emp_obj.country = country
        emp_obj.email = email
        emp_obj.account = account
        emp_obj.bank = bank
        emp_obj.pfaccount = pfaccount
        emp_obj.joining_date = joining_date

        emp_obj.user_name_id = Regis_db.objects.filter(username=request.session['u'])[0].id

        emp_obj.save()

        messages.success(request, 'saved')
        return render(request, 'employee/emp_management.html')

    return render(request, 'employee/emp_management.html', {'data': s})


def salary_detail(request, x=-1):
    e = salary_details.objects.filter(user_name=Regis_db.objects.filter(username=request.session['u'])[0].id)
    print(e)
    return render(request, 'employee/salary_details.html', {'data': e})


#
# def logout(request):
#     auth.logout(request)
#     return render(request, 'employee/emp_logout.html')


def view_details(request):
    e = emp_account.objects.filter(user_name=Regis_db.objects.filter(username=request.session['u'])[0].id)

    s = Regis_db.objects.filter(username=request.session['u'])

    return render(request, 'employee/view_details.html', {'data': e, 'data1': s})


def view_salary(request, x):
    e = salary_details.objects.filter(id=x)
    obj = emp_account.objects.filter(user_name=Regis_db.objects.filter(username=request.session['u'])[0].id)

    return render(request, 'employee/view_salary.html', {"sal": e, 'emp': obj})


def delete_data(request, x):
    e = salary_details.objects.filter(id=x)
    e.delete()
    return redirect('empurl:salary_details')

kamlesh_friend/employee/templates/employee/aboutme.html
{% extends 'employee/emp.html'%}
{%load static%}
{% block body%}

<div class="container-fluid" style="background-color:#64677F;height:60px">
    <div class="col-sm-4">
        <h3 class="animated bounceInLeft" align="center" style="color:white;hight:40px;padding-top:10px">About</h3>


    </div>
</div>

<div class="container" style="padding-top:90px">
    <div class="row">

        <div class="col-sm-6" style="padding-left:40px">
            <img class="rounded-circle animated bounceInLeft" style="float:right;"
                 src="{% static 'homepage/images/about_logo.jpg' %}"
                 width="500" height="400px">


        </div>
        <div class="col-sm-6">

            <h1 class="animated bounceInRight" style="font-size:25px;color:gray;" class="Monospace">
                About Payroll Management System
            </h1>
            <hr>
            <p class="animated bounceInRight" style="font-size:15px;color:#8D88A2">Payroll Management Sysytem is an
                important activity in any
                organization. The main objective of this project Pyaroll Manangement Sysytem is to managing employee's
                information of organization or for a small group. It has to store all the records of every employee
                within the organization to assign work to person and right salary and perks to their
                eligible emplooyees .It can also manage employee information efficiently, define the emoluments,
                deductions,leave, tax etc, generate pay slip, generate
                and manage the payrolls processes according to the salary structure assigned to the employee, etc. It
                keeps a track of the employees attendance and so on that basis it generate the monthly salary. </p>

            <img class="animated bounceInRight" style="padding-left:70px;float:left;"
                 src="{% static 'homepage/images/pic.gif' %}" width="400"
                 height="250px">

        </div>

    </div>
</div>
{%endblock%}

kamlesh_friend/employee/templates/employee/change_password.html
{% extends 'employee/emp.html'%}
{% load static %}

<title>{% block title %}Change Password{% endblock %}</title>
<link rel="stylesheet" type="text/css" href="{% static 'homepage/login.css' %}"/>
<script src="{% static 'homepage/login.js' %}" type="text/javascript"></script>

{%block body%}


<div class="container-fluid" style="background-color:#64677F;height:60px">
    <div class="col-sm-4">
        <h3 class="animated bounceInLeft" align="center" style="color:white;hight:40px;padding-top:10px">CHANGE
            PASSWORD</h3>


    </div>
</div>
<br>
<br>
<br>
<br>

<div class="container">
    <div align="center">

        <div class="card" style="width:500px">
            <div class="bg-dark text-white card-header">Change Password</div>
            <div class="card-body">
                <form name="myform" method="post">
                    {%csrf_token%}

                    <div class="form-group">

                        <input id="password" name="password" class="form-control" type="password"
                               required placeholder="Password">
                        <span id="error_name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input id="password_confirm" name="password_confirm" class="form-control" type="password"
                               required placeholder="password_confirm">
                        <span id="error_lastname" class="text-danger"></span>
                    </div>
                    <button id="submit" type="submit" value="submit" class="btn btn-dark">Submit</button>
                    {% if messages %}

                    {% for message in messages %}
                    <div class="alert alert-warning alert-dismissible {{ message.tags }}">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <strong>{{message}}</strong>
                    </div>
                    {%endfor%}


                    {% endif %}
                    <script>
    $(function () {
        $("#submit").click(function () {
            var password = $("#password").val();
            var confirmPassword = $("#password_confirm").val();
            if (password != confirmPassword) {
                alert("Passwords do not match.");
                return false;
            }
            return true;
        });
    });







                    </script>
                </form>


            </div>
            <div class="bg-dark text-white card-footer"></div>
        </div>
    </div>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
{%endblock%}

kamlesh_friend/employee/templates/employee/emp_management.html
{% extends 'employee/emp.html'%}
{%load static%}
{% block body%}
<style>
hr{
margin-top:3px;
}
select{
width:100%;
height:37px;
border-radius:4px;
border-color:lightgray;
}










</style>

<div class="container-fluid" style="background-color:#64677F;height:60px">
    <div class="col-sm-4">
        <h3 class="animated bounceInLeft" align="center" style="color:white;hight:40px;padding-top:10px">EMPLOYEE
            MANAGEMENT</h3>
    </div>
</div>
<br>

<div class="container">
    <div align="center">


        <div class="card" style="width:900px">
            <div class="bg-dark text-white card-header" style="text-transform: uppercase;">UPDATE DETAILS OF
                {{info.fullname}}
            </div>
            <div class="card-body">
                <form id="sign_up" name="myform" method="post" enctype="multipart/form-data">
                    {%csrf_token%}
                    <p style="float:left"><b>Employee Login Details</b></p>
                    <br>
                    <hr>

                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">

                                <label style="float:left;">User Full Name</label>
                                <br>


                                <input id="fullname" name="fullname" class="form-control" type="text"
                                       data-validation="required" placeholder="fullname">


                                <span id="error" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-sm-6">


                            <div class="form-group">
                                <label style="float:left;">Username</label>
                                <br>

                                {%for data in data%}
                                <input id="username1" name="username1" class="form-control" type="text"
                                       data-validation="required" placeholder="{{data.username}}">
                                {%endfor%}


                                <span id="error_lastname" class="text-danger"></span>
                            </div>

                        </div>
                    </div>


                    <p style="float:left"><b>Employee Personal Details</b></p>
                    <br>
                    <hr>

                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label style="float:left;">Department</label>
                                <br>


                                <select style="float:left;" name="department">
                                    <option value="Account Department">Account Department</option>
                                    <option value="HR Department">HR Department</option>
                                    <option value="Technical Department">Technical Department</option>

                                </select>

                            </div>

                        </div>

                        <div class="col-sm-6">
                            <div class="form-group">
                                <label style="float:left;">Designation</label>
                                <br>


                                <select style="float:left;" name="designation">
                                    <option value="Manager">Manager</option>
                                    <option value="Accountant">Accountant</option>
                                    <option value="Employee">Employee</option>
                                    <option value="Peon">Peon</option>

                                </select>

                            </div>

                        </div>
                    </div>


                    <br>


                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label style="float:left;">Gender</label>
                                <br>


                                <input type="radio" name="gender" value="male"> Male
                                <input type="radio" name="gender" value="female"> Female


                            </div>

                        </div>

                        <div class="col-sm-6">
                            <div class="form-group">
                                <label style="float:left;">User Email</label>
                                <br>
                                {%for data in data%}
                                <input id="email" name="email" class="form-control" type="email"
                                       data-validation="required" placeholder='{{data.email}}' value='{{data.email}}'>
                                {%endfor%}
                                <span id="error_lastname2" class="text-danger"></span>
                            </div>


                        </div>
                    </div>


                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label style="float:left;">User Mobile Number</label>
                                <br>
                                <input pattern="[1-9]{1}[0-9]{9}" id="mobile" name="mobile" class="form-control"
                                       type="text"
                                       data-validation="required" placeholder="{{mobile}}" maxlength="10">
                                <span id="www" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-sm-6">


                            <div class="form-group">
                                <label style="float:left;">User Date Of Birth</label>
                                <br>
                                <input id="bday" name="bday" class="form-control"
                                       type="date"
                                       data-validation="required" placeholder="DOB">
                                <span id="error_lastname7" class="text-danger"></span>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label style="float:left;">Address Line 1</label>
                                <br>
                                <input id="add1" name="add1" class="form-control"
                                       type="text"
                                       data-validation="required" placeholder="Address">
                            </div>
                        </div>
                        <div class="col-sm-6">


                            <div class="form-group">
                                <label style="float:left;">Address Line 2</label>
                                <br>
                                <input id="add2" name="add2" class="form-control"
                                       type="text"
                                       placeholder="Optional">
                            </div>
                        </div>
                    </div>


                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label style="float:left;">City</label>
                                <br>
                                <select style="float:left;" name="city">
                                    <option value="Delhi">Delhi</option>
                                    <option value="Dehradun">Dehradun</option>
                                    <option value="Chennai">Chennai</option>
                                    <option value="Jaipur">Jaipur</option>
                                    <option value="Mumbai">Mumbai</option>
                                    <option value="Other">Other</option>

                                </select>
                            </div>
                            <br>
                            <div class="form-group">
                                <label style="float:left;">State</label>
                                <br>
                                <select style="float:left;" name="state">
                                    <option value="Uttarakhand">Uttarakhand</option>
                                    <option value="Tamilnadu">Tamilnadu</option>
                                    <option value="Kolkata">Kolkata</option>
                                    <option value="Maharstra">Maharstra</option>
                                    <option value="Punjab">Punjab</option>
                                    <option value="Other">Other</option>

                                </select>
                            </div>
                            <br>
                            <div class="form-group">
                                <label style="float:left;">Country</label>
                                <br>
                                <select style="float:left;" name="country" value="{{info.country}}">
                                    <option value="India">India</option>
                                    <option value="USA">USA</option>
                                    <option value="Pakistan">Pakistan</option>
                                    <option value="Nepal">Nepal</option>
                                    <option value="Sri Lanka">Sri Lanka</option>
                                    <option value="Bangladesh">Bangladesh</option>
                                    <option value="Other">Other</option>

                                </select>
                            </div>
                        </div>
                        <div class="col-sm-6">


                            <div class="form-group">
                                <label style="float:left;">User Profile</label>
                                <br>
                                <input style="float:left;width:100%; border:3px solid #fafafa;border-radius:4px;border-color:lightgray;"
                                       type="file" name="filename" accept="image/gif, image/jpeg, image/png">
                            </div>
                        </div>
                    </div>
                    <br>
                    <p style="float:left"><b>Employee Account Details</b></p>
                    <br>
                    <hr>

                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label style="float:left;">Account Number</label>
                                <br>
                                <input id="account" name="account" class="form-control"
                                       type="number"
                                       data-validation="required" placeholder="{{info.account}}">
                            </div>
                        </div>
                        <div class="col-sm-6">


                            <div class="form-group">
                                <label style="float:left;">Bank Name</label>
                                <br>
                                <input id="bank" name="bank" class="form-control"
                                       type="text" data-validation="required"
                                       placeholder="{{info.bank}}">
                            </div>
                        </div>
                    </div>


                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label style="float:left;">Pf Account</label>
                                <br>
                                <input id="pfaccount" name="pfaccount" class="form-control"
                                       type="number"
                                       data-validation="required" placeholder="{{info.pfaccount}}">
                            </div>
                        </div>
                        <div class="col-sm-6">


                            <div class="form-group">
                                <label style="float:left;">Date Of Joining</label>
                                <br>
                                <input id="joining_date" name="joining_date" class="form-control"
                                       type="date" data-validation="required"
                                       placeholder={{info.joining_date}}>
                            </div>
                        </div>
                    </div>


                    <button id="submit" type="submit" value="submit" class="btn btn-dark">Submit</button>
                    {% if messages %}

                    {% for message in messages %}
                    <div class="alert alert-warning alert-dismissible {{ message.tags }}">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <strong>{{message}}</strong>
                    </div>
                    {%endfor%}


                    {% endif %}
                </form>
                <hr>
                <a href="{% url 'empurl:view_details' %}"> <img src="{% static 'employee/images/click.png' %}">Click
                    Here
                    For View Details</a>


            </div>
            <div class="bg-dark text-white card-footer">

            </div>

        </div>

    </div>
</div>


{%endblock%}

kamlesh_friend/employee/templates/employee/salary_details.html
{% extends 'employee/emp.html'%}
{%load static%}

{% block body%}
<div class="container-fluid" style="background-color:#64677F;height:60px">
    <div class="col-sm-4">
        <h3 class="animated bounceInLeft" align="center" style="color:white;hight:40px;padding-top:10px">SALARY
            DETAILS</h3>
    </div>
</div>
<br>

<div class="container">
    <table class="table table-striped table-responsive">
        <thead class="bg-dark" style="color:white;">
        <tr>
            <th>S NO.</th>
            <th>Employee Name</th>
            <th>Month Of Salary</th>
            <th>Basic Salary</th>
            <th>Work Days</th>
            <th>Salary Total</th>
            <th>Year Of Salary</th>
            <th>Action</th>

        </tr>
        </thead>
        <tbody>
        <tr>
            {%for data in data%}

            <td>{{ forloop.counter }}</td>

            <td>{{data.emp_name}}</td>
            <td>{{data.mp}}</td>
            <td>{{data.bs}}</td>
            <td>{{data.working_days}}</td>
            <td>{{data.total_salary}}</td>
            <td>{{data.year_salary}}</td>

            <td>
                <div class="btn-group inline pull-left">

                    <form action="/remove_items/" method="post">


                        <a href="{% url 'empurl:view_salary' data.id %}">
                            <button type="button" class="btn btn-info">Salary Slip</button>
                        </a>

                        <a href="{% url 'empurl:delete_data' data.id %}">
                            <button type="button" class="btn btn-danger ">Delete</button>
                        </a>
                    </form>
                </div>
            </td>

        </tr>
        {%endfor%}
        </tbody>
    </table>
</div>
{%endblock%}

kamlesh_friend/employee/templates/employee/view_details.html
{% extends 'employee/emp.html'%}
{%load static%}
{% block body%}

<div class="container-fluid" style="background-color:#64677F;height:60px">
    <div class="col-sm-4">
        <h3 class="animated bounceInLeft" align="center" style="color:white;hight:40px;padding-top:10px">Details</h3>
    </div>
</div>
<br>

{%for data in data%}
<div class="container">
    <div align="center">


        <div class="card" style="width:900px">
            <div class="bg-dark text-white card-header" style="text-transform: uppercase;">VIEW DETAILS OF
                {{data.fullname}}
            </div>
            <div class="card-body">
                <p style="text-transform: uppercase" ;><b>{{data.fullname}}</b></p><br>
                <img src="{{data.filename.url}}" style="width:90px;height:90px;"><br><br>
                {%for data in data1%}
                <p><b>Email:</b>{{data.email}}</p>
                {%endfor%}
                <p><b>Mobile No</b>.{{data.mobile}}</p>

                <p><b>Gender:</b>{{data.gender}}</p>
                <p><b>Date Of Birth:</b>{{data.bday}}</p>
                <p><b>Address:</b>{{data.add1}}</p>
                <hr>
                <div class="row">
                    <div class="col-sm-6">
                        <p><b>Department:</b>{{data.department}}</p>

                    </div>
                    <div class="col-sm-6">
                        <p><b>Designation:</b>{{data.designation}}</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <p><b>State:</b>{{data.state}}</p>

                    </div>
                    <div class="col-sm-6">
                        <p><b>City:</b>{{data.city}}</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <p><b>Account Number:</b>{{data.account}}</p>

                    </div>
                    <div class="col-sm-6">
                        <p><b>PF Account:</b>{{data.pfaccount}}</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <p><b>Bank Name:</b>{{data.bank}}</p>

                    </div>
                    <div class="col-sm-6">
                        <p><b>Joining Date:</b>{{data.joining_date}}</p>
                    </div>
                </div>
                <hr>
                <a href="{% url 'empurl:emp_details' %}"> <img src="{% static 'employee/images/click.png' %}">Click Here
                    For Update Details</a>


            </div>
        </div>
    </div>
</div>
{%endfor%}
{%endblock%}